### ISSUE TITLE
Environments not showing up in the package manager while included in Jupyterlab

### ISSUE THREAD

**Issue by Siva10** [fcollonval/jupyter_conda#5] opened 2019-02-20 09:19 UTC
I'm trying to include this extension to my jupyterlab since I'm trying to manage the environments through UI. While trying out to install with the following steps in jupyterlab terminal
```
conda install -c conda-forge jupyter_conda
jupyter labextension install jupyterlab_toastify jupyterlab_conda
```
the **Conda packages manager** under **Settings** is not listing the environments available. Though I'm able to see the environments by executing the command in the terminal 

`conda info --envs`

Not sure what I'm missing. Any help would be great ?

**Comment by fcollonval** [comment] 2019-02-20 11:19
@Siva10 did you get any error when executing

`jupyter labextension install jupyterlab_toastify jupyterlab_conda`

Could you also provide

* the results of
`jupyter labextension list`
* the version of jupyterlab
* Any errors that show in the Webbrowser console when starting jupyterlab - on chrome you could bring that up by pressing F12

This helps finding the problem root cause.
Thanks

**Comment by Siva10** [comment] 2019-02-21 02:14
@fcollonval Thanks for the reply. 

I didn't see any error msgs while installing the extensions, only warnings though.

- Results of `jupyter labextension list`
```JupyterLab v0.35.4
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @sap/databaseexplorer v1.0.169  enabled  OK
        jupyterlab_conda v0.6.0  enabled  OK
        jupyterlab_hanadataframeinspector v0.1.0  enabled  OK
        jupyterlab_toastify v2.2.0  enabled  OK
        theme-fiori-extension v0.1.3  enabled  OK```

- Jupyterlab version `JupyterLab v0.35.4`

- Was able to see the following errors in console

```Uncaught (in promise) Error: An error occurred while listing Conda environments.
    at CondaEnvironments.<anonymous> (services.js:181)
    at Generator.throw (<anonymous>)
    at rejected (services.js:5)```

**Comment by fcollonval** [comment] 2019-02-22 13:37
Unfortunately, not so useful... I need to provide better error message; my
bad.

Could you look in the terminal server if there is an error message too?

Other questions:
* is jupyterlab running in an environment that is not the base one?
* Could you execute `!conda info --envs` in a notebook or python console
with the default kernel to see if an error pops up?

Cheers

**Comment by Siva10** [comment] 2019-02-23 02:30
I ran the command `! conda info --envs` in a notebook cell and got the following output, so looks like its running in the base env

```# conda environments:
#
base                  *  /opt/conda
python2                  /opt/conda/envs/python2
test-env-user            /opt/conda/envs/test-env-user```

**Comment by fcollonval** [comment] 2019-02-24 11:44
Ok let's try to identify what's going on.

Could you please execute within JupyterLab notebook or Python console the following:

```python
from subprocess import Popen, PIPE
import json

process = Popen(["conda", "info", "--json"], stdout=PIPE, stderr=PIPE)
output, error = process.communicate()
output = output.decode("utf-8")
print(output)

JSONISH_RE = r'(^\s*["\{\}\[\],\d])|(["\}\}\[\],\d]\s*$)'
def clean_conda_json(output):
    lines = output.splitlines()

    try:
        return json.loads("\n".join(lines))
    except (ValueError, json.JSONDecodeError) as err:
        print("[jupyter_conda] JSON parse fail:\n%s", err)

    # try to remove bad lines
    lines = [line for line in lines if re.match(JSONISH_RE, line)]

    try:
        return json.loads("\n".join(lines))
    except (ValueError, json.JSONDecodeError) as err:
        print("[jupyter_conda] JSON clean/parse fail:\n%s", err)

    return {"error": True}

clean_conda_json(output)
```
This is the code called by the API to list the environments. Hopefully we will get better error description to figure out the problem and a potential fix.

**Comment by Siva10** [comment] 2019-02-26 02:09
I got the following output by running the code above in the terminal 
```
{
  "GID": 100,
  "UID": 1000,
  "active_prefix": null,
  "active_prefix_name": null,
  "channels": [
    "https://conda.anaconda.org/conda-forge/linux-64",
    "https://conda.anaconda.org/conda-forge/noarch",
    "https://repo.anaconda.com/pkgs/main/linux-64",
    "https://repo.anaconda.com/pkgs/main/noarch",
    "https://repo.anaconda.com/pkgs/free/linux-64",
    "https://repo.anaconda.com/pkgs/free/noarch",
    "https://repo.anaconda.com/pkgs/r/linux-64",
    "https://repo.anaconda.com/pkgs/r/noarch",
    "https://repo.anaconda.com/pkgs/pro/linux-64",
    "https://repo.anaconda.com/pkgs/pro/noarch"
  ],
  "conda_build_version": "not installed",
  "conda_env_version": "4.5.11",
  "conda_location": "/opt/conda/lib/python3.6/site-packages/conda",
  "conda_prefix": "/opt/conda",
  "conda_private": false,
  "conda_shlvl": 0,
  "conda_version": "4.5.11",
  "config_files": [
    "/opt/conda/.condarc"
  ],
  "default_prefix": "/opt/conda",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "CONDA_BACKUP_ADDR2LINE": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-addr2line",
    "CONDA_BACKUP_AR": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ar",
    "CONDA_BACKUP_AS": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-as",
    "CONDA_BACKUP_CC": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cc",
    "CONDA_BACKUP_CFLAGS": "-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe",
    "CONDA_BACKUP_CPP": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cpp",
    "CONDA_BACKUP_CPPFLAGS": "-DNDEBUG -D_FORTIFY_SOURCE=2 -O2",
    "CONDA_BACKUP_CXX": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++",
    "CONDA_BACKUP_CXXFILT": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++filt",
    "CONDA_BACKUP_CXXFLAGS": "-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe",
    "CONDA_BACKUP_DEBUG_CFLAGS": "-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe",
    "CONDA_BACKUP_DEBUG_CPPFLAGS": "-DNDEBUG -D_FORTIFY_SOURCE=2 -O2",
    "CONDA_BACKUP_DEBUG_CXXFLAGS": "-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe",
    "CONDA_BACKUP_ELFEDIT": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-elfedit",
    "CONDA_BACKUP_GCC": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc",
    "CONDA_BACKUP_GCC_AR": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ar",
    "CONDA_BACKUP_GCC_NM": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-nm",
    "CONDA_BACKUP_GCC_RANLIB": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib",
    "CONDA_BACKUP_GPROF": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gprof",
    "CONDA_BACKUP_GXX": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-g++",
    "CONDA_BACKUP_HOST": "x86_64-conda_cos6-linux-gnu",
    "CONDA_BACKUP_LD": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld",
    "CONDA_BACKUP_LDFLAGS": "-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags",
    "CONDA_BACKUP_LD_GOLD": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld.gold",
    "CONDA_BACKUP_NM": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-nm",
    "CONDA_BACKUP_OBJCOPY": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objcopy",
    "CONDA_BACKUP_OBJDUMP": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objdump",
    "CONDA_BACKUP_RANLIB": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ranlib",
    "CONDA_BACKUP_READELF": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-readelf",
    "CONDA_BACKUP_SIZE": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-size",
    "CONDA_BACKUP_STRINGS": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strings",
    "CONDA_BACKUP_STRIP": "/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strip",
    "CONDA_BACKUP__CONDA_PYTHON_SYSCONFIGDATA_NAME": "_sysconfigdata_x86_64_conda_cos6_linux_gnu",
    "CONDA_DIR": "/opt/conda",
    "CONDA_ROOT": "/opt/conda",
    "CONDA_SHLVL": "0",
    "PATH": "/opt/conda/bin:/opt/conda/bin:/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "REQUESTS_CA_BUNDLE": "<not set>",
    "SSL_CERT_FILE": "<not set>"
  },
  "envs": [
    "/opt/conda",
    "/opt/conda/envs/python2",
    "/opt/conda/envs/test-env-user"
  ],
  "envs_dirs": [
    "/opt/conda/envs",
    "/home/labuser/.conda/envs"
  ],
  "netrc_file": null,
  "offline": false,
  "pkgs_dirs": [
    "/opt/conda/pkgs",
    "/home/labuser/.conda/pkgs"
  ],
  "platform": "linux-64",
  "python_version": "3.6.7.final.0",
  "rc_path": "/home/labuser/.condarc",
  "requests_version": "2.21.0",
  "root_prefix": "/opt/conda",
  "root_writable": true,
  "site_dirs": [],
  "sys.executable": "/opt/conda/bin/python",
  "sys.prefix": "/opt/conda",
  "sys.version": "3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]",
  "sys_rc_path": "/opt/conda/.condarc",
  "user_agent": "conda/4.5.11 requests/2.21.0 CPython/3.6.7 Linux/4.4.111+ opensuse-leap/15.0 glibc/2.26",
  "user_rc_path": "/home/labuser/.condarc"
}
```

**Comment by fcollonval** [comment] 2019-03-10 12:19
Hey 
I did a couple of tests. No errors appear for me.

In the Jupyter server log, is there some error like the following:
```
[W 13:15:37.267 LabApp] Error loading server extension jupyter_conda
    Traceback (most recent call last):
      File "C:\Users\freud\Anaconda3\envs\nb_conda\lib\site-packages\notebook\notebookapp.py", line 1573, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\freud\Anaconda3\envs\nb_conda\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_conda'
```
or
```
[W 13:15:39.225 LabApp] 404 GET /conda/environments
```

If you see those, that means the server extension side is not properly installed. You could try to reinstall the `jupyter_conda` package.

**Comment by amoshche** [comment] 2019-03-24 21:13
I am having similar problem
`(notebook) C:\export\home\jupyter\notebook>jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: C:\export\conda\envs\notebook\share\jupyter\lab
        jupyterlab_conda v0.6.0 enabled  ok
        jupyterlab_toastify v2.2.0 enabled  ok

(notebook) C:\export\home\jupyter\notebook>conda info --envs
# conda environments:
#
base                     C:\export\apps\dbConda
node8                    C:\export\conda\envs\node8
notebook              *  C:\export\conda\envs\notebook
py27                     C:\export\conda\envs\py27
py36                     C:\export\conda\envs\py36

!!!!Error come here which seems to prevent the functionality
    loadEnvironments() {
...
>>>                           if (env.is_default) {
>>>                               newState.currentEnvironment = env.name;
>>>                           }
and if it is not default the property is not set, so buuum!
>>>>>      newState.channels = yield this.props.model.getChannels(newState.currentEnvironment);
                catch (error) {
>>>>>           jupyterlab_toastify_1.INotification.error(error.message);
                }
`

Also I do see in environments only one which is base I do not see others
`
newState.environments
[{…}]0: {name: "base", dir: "C:\export\apps\dbConda", is_default: false}length: 1__proto__: Array(0)
`

**Comment by sbaehr** [comment] 2019-03-26 14:19
Just to pile on here, having what appears to be the same issue : ) . Can't see any other environments in package manager besides base. 

Vanilla install of JupyterHub/Lab and jupyter_conda, here is the output of `jupyter labextension list`:
```
JupyterLab v0.35.3
Known labextensions:
   app dir: /opt/anaconda/share/jupyter/lab
        @jupyterlab/hub-extension v0.12.0  enabled  OK
        jupyterlab_conda v0.6.0  enabled  OK
        jupyterlab_toastify v2.2.0  enabled  OK
```

Output from `!conda info --envs` in notebook:
```
# conda environments:
#
test_2                   /home/sbaehr/.conda/envs/test_2
test_3                   /home/sbaehr/.conda/envs/test_3
test_env                 /home/sbaehr/.conda/envs/test_env
base                  *  /opt/anaconda
```

When I create an env in UI, it *does* successfully create it, but it 
1) does not show in package manager
2) jupyter console output shows the following error:
```
[E 2019-03-26 14:16:44.381 SingleUserLabApp web:1670] Uncaught exception GET /user/sbaehr/conda/packages/test_4/available?1553609778545 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='10.43.21.20:8788', method='GET', uri='/user/sbaehr/conda/packages/test_4/available?1553609778545', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/anaconda/lib/python3.7/types.py", line 210, in throw
        return self.__wrapped.throw(tp, *rest)
      File "/opt/anaconda/lib/python3.7/site-packages/jupyter_conda/handlers.py", line 199, in get
        data = yield self.env_manager.list_available(env)
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/anaconda/lib/python3.7/site-packages/jupyter_conda/envmanager.py", line 306, in list_available
        channels = yield self.env_channels(env)
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
        yielded = self.gen.send(value)
      File "/opt/anaconda/lib/python3.7/site-packages/jupyter_conda/envmanager.py", line 166, in env_channels
        old_prefix = os.environ["CONDA_PREFIX"]
      File "/opt/anaconda/lib/python3.7/os.py", line 678, in __getitem__
        raise KeyError(key) from None
    KeyError: 'CONDA_PREFIX'
```

Happy to quickly supply whatever is needed to get to the bottom of this, thanks!

**Comment by fcollonval** [comment] 2019-03-31 08:46
Hey @amoshche and @sbaehr,
Thanks you for reporting the error.

I hope to have cornered the error. Could you try the version in branch `5-env-not-shown` (see command below to install it).
```
pip install git+https://github.com/fcollonval/jupyter_conda.git@5-env-not-shown
```

Some comments for @sbaehr 
- I encountered that once but I was unable to correct or reproduce it. I succeed to remove the error by *removing the workspace file and clearing Jupyter Lab local storage*. That error is quite a mystery. Somehow JupyterLab keep track of the conda manager being opened. But it does not load it at startup.
- The error you are seeing comes from the algorithm. I try to load `channeldata.json` from all used channels to get a description for the packages - if an error occurs it will be skipped.
- What worry me in your first post, is the key error `CONDA_PREFIX` not found. This environment variable is not present in your configuration. Normally it is set when loading conda in the console. Does this mean that conda is not loaded in the console launching JupyterLab?

Cheers

**Comment by amoshche** [comment] 2019-04-02 09:20
Hello, the given branch solves the envs problem
Thank you!

**Comment by sbaehr** [comment] 2019-04-04 18:39
@fcollonval , thank you for your attention. That CONDA_PREFIX error persists, unfortunately. I did a fresh install of the following, in order:
* install of anaconda
* install of jupyterhub
* install of jupyterlab
* install of jupyter_conda and its lab extension

I am running jupyterhub/lab via sudo, in case that could matter. In the conda environment manager in jupyterlab, I can see my two envs, base and test1. If I click on test1 entry, the error is thrown as before:
`[E 2019-04-04 18:34:03.684 SingleUserNotebookApp web:1788] Uncaught exception GET /user/sbaehr/conda/environments/test1/channels?1554402843500 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='10.43.21.20:8788', method='GET', uri='/user/sbaehr/conda/environments/test1/channels?1554402843500', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/anaconda/lib/python3.7/site-packages/jupyter_conda/handlers.py", line 77, in get
        channels = yield self.env_manager.env_channels(env)
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
        value = future.result()
      File "/opt/anaconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.send(value)
      File "/opt/anaconda/lib/python3.7/site-packages/jupyter_conda/envmanager.py", line 166, in env_channels
        old_prefix = os.environ["CONDA_PREFIX"]
      File "/opt/anaconda/lib/python3.7/os.py", line 678, in __getitem__
        raise KeyError(key) from None
    KeyError: 'CONDA_PREFIX'
[W 2019-04-04 18:34:03.686 SingleUserNotebookApp handlers:620] Unhandled error
[E 2019-04-04 18:34:03.687 SingleUserNotebookApp log:150] {
      "Cache-Control": "no-cache",
      "Pragma": "no-cache",
      "Cookie": "jupyterhub-user-sbaehr=2|1:0|10:1554402750|22:jupyterhub-user-sbaehr|48:OWE2Y2ViNDEtMWQ5MC00OTQ2LThlMjItMDU4NmU2ZWRjYjc0|b487a0cf7b266dcaafca1c727ee8ffedca9b7abdf80bd1a35ff0506b379b2114; _xsrf=2|abd9a47c|9e5e755f9e2f978cefe1ba3852a04c66|1553277683; jupyterhub-session-id=297502720d30401688962440d2867670",
      "Connection": "close",
      "Dnt": "1",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|abd9a47c|9e5e755f9e2f978cefe1ba3852a04c66|1553277683",
      "Referer": "http://10.43.21.20:8788/user/sbaehr/lab?redirects=1",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0",
      "Host": "10.43.21.20:8788"
    }
[E 2019-04-04 18:34:03.687 SingleUserNotebookApp log:158] 500 GET /user/sbaehr/conda/environments/test1/channels?1554402843500 (sbaehr@127.0.0.1) 169.92ms
`

**Comment by sbaehr** [comment] 2019-04-04 20:24
Update - I was able to find a workaround, but it doesn't really illuminate the original cause of the problem. I included `c.Spawner.environment = {'CONDA_PREFIX':'/opt/anaconda'} ` in my jupyterhub config, to be passed to the single user jupyter notebook server.

Let me know if you'd like me to help root out the cause, but I do have a functional install now in either case.

**Comment by fcollonval** [comment] 2019-04-05 14:06
hey @sbaehr, okay the error is related to JupyterHub and specifically the environment variables pass to the spawned server. In a user notebook server could you list the environment variables (execute `!export` in a cell) and see if some `CONDA_` variables are transferred by default. If none are passed, this explain the error.

But anyway to be more robust, I modify the code to have it optional. So could you please try the branch to see if it fixes the error in your case?

```
pip install git+https://github.com/fcollonval/jupyter_conda.git@5-env-not-shown
```

**Comment by sbaehr** [comment] 2019-04-05 14:24
I unset that jupyterhub config workaround I'd mentioned. Now, inexplicably (without installing latest on that branch) I *don't* get the CONDA_PREFIX error, and `!export` shows as below (notice that CONDA_PREFIX is present and set). I must have changed the way I was running it, I'm really at a loss to say what's happened. 
```
export CLICOLOR='1'
export CONDA_PREFIX='/opt/anaconda'
export GIT_PAGER='cat'
export HOME='/home/sbaehr'
export JPY_API_TOKEN='blahblah'
export JPY_PARENT_PID='11716'
export JUPYTERHUB_API_TOKEN='blahblah'
export JUPYTERHUB_API_URL='http://127.0.0.1:8081/hub/api'
export JUPYTERHUB_BASE_URL='/'
export JUPYTERHUB_CLIENT_ID='jupyterhub-user-sbaehr'
export JUPYTERHUB_HOST=''
export JUPYTERHUB_OAUTH_CALLBACK_URL='/user/sbaehr/oauth_callback'
export JUPYTERHUB_SERVICE_PREFIX='/user/sbaehr/'
export JUPYTERHUB_USER='sbaehr'
export LANG='C.UTF-8'
export MPLBACKEND='module://ipykernel.pylab.backend_inline'
export PAGER='cat'
export PATH='/opt/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin'
export PWD='/home/sbaehr'
export SHELL='/bin/bash'
export TERM='xterm-color'
export USER='sbaehr'
```

**Comment by fcollonval** [comment] 2019-04-06 14:49
Strange that only CONDA_PREFIX is showing. They should be more. But at least I now know that in juputerhub use case, I should not rely on environment variables. Thx for the feedback. I'll release soon a patch version. And close this issue.

**Closed by fcollonval** 2019-04-06 14:49 UTC
Labels: bug

**Comment by nehalecky** [comment] 2019-04-06 18:01
Cool to see progress here! I'm unclear, is this issue actually resolved?

**Comment by fcollonval** [comment] 2019-04-10 10:40
Hey @nehalecky, this is considered as resolved. A fix release will follow soon.

If you still have a problem, please open a new issue.

**Comment by nehalecky** [comment] 2019-04-16 05:21
OK, @fcollonval, thank you for the update, and look forward to the release!

**Comment by fcollonval** [comment] 2019-04-17 18:56
Hey, I released v2.4.2 containing the fix.
Cheers
